"""Add created_at and is_read to appointments

Revision ID: 464714074d3c
Revises: 
Create Date: 2025-08-29 11:08:46.437368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464714074d3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
